name: Test

on:
  push:
    branches: ["main"]
    tags: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        # TODO:
        # > listen-3.2.1 requires ruby version >= 2.2.7, ~> 2.2, which is incompatible with
        # ruby: [2.7, head]
        ruby: [2.7]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle config set path vendor/bundle
      - run: bundle install
        working-directory: test
      - run: bundle exec rake
